In [1]:
import numpy as np

# 行列の定義

二重リストを`np.matrix`に与える

In [2]:
A = np.matrix([
    [3., 1., 2.],
    [2., 3., 1.]
])

In [3]:
B = np.matrix([
    [1 + 2j, 1 - 1j],
    [3j    , 2 + 1j]
])

In [4]:
A

matrix([[3., 1., 2.],
        [2., 3., 1.]])

In [5]:
B

matrix([[1.+2.j, 1.-1.j],
        [0.+3.j, 2.+1.j]])

## 単位行列の定義

In [6]:
I = np.identity(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 定数倍

左から定数をかける

In [7]:
2*A

matrix([[6., 2., 4.],
        [4., 6., 2.]])

# 行列同士の加減

In [8]:
A + A

matrix([[6., 2., 4.],
        [4., 6., 2.]])

In [9]:
A - A

matrix([[0., 0., 0.],
        [0., 0., 0.]])

# 行列の積

In [10]:
np.matmul(B, B)

matrix([[ 0.+7.j,  6.+0.j],
        [-9.+9.j,  6.+7.j]])

# 行列のHadamard積

In [11]:
np.multiply(A, A)

matrix([[9., 1., 4.],
        [4., 9., 1.]])

In [12]:
np.multiply(B, B)

matrix([[-3.+4.j,  0.-2.j],
        [-9.+0.j,  3.+4.j]])

# 転置・Helmite転置

- `np.transpose(...)`: 転置
- `np.conjugate(...)`: Helmite転置

In [13]:
At = np.transpose(A)

In [14]:
At

matrix([[3., 2.],
        [1., 3.],
        [2., 1.]])

In [15]:
Bt = np.conjugate(B)

In [16]:
Bt

matrix([[1.-2.j, 1.+1.j],
        [0.-3.j, 2.-1.j]])

# 逆行列

`linalg`(LINear ALGebra)ライブラリを使う

In [17]:
Binv = np.linalg.inv(B)

In [18]:
Binv

matrix([[-0.30769231-0.53846154j,  0.38461538-0.07692308j],
        [-0.46153846+0.69230769j,  0.07692308-0.61538462j]])

In [19]:
np.matmul(B, Binv)

matrix([[ 1.00000000e+00-5.55111512e-17j,
         -5.55111512e-17+0.00000000e+00j],
        [-1.11022302e-16+0.00000000e+00j,
          1.00000000e+00+0.00000000e+00j]])

正方行列ではなければ失敗する

In [20]:
np.linalg.inv(A)

LinAlgError: Last 2 dimensions of the array must be square

# 行列式をもとめる

In [21]:
np.linalg.det(B)

(-3.000000000000001+1.9999999999999998j)